# Generated by Django 6.0.6 on 2026-06-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_news_promotion_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='tovar',
            field=models.ManyToManyField(blank=True, to='products_app.tovar', verbose_name='Товары по акции'),
        ),
    ]
