# Generated by Django 6.0.6 on 2026-06-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_order_pos_order_order_tovar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pos_order',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказов'},
        ),
    ]
