from .views import *
from django.urls import path, include

urlpatterns = [
    path('', info_view, name='info_view'),
    path('cart/', cart_view, name='cart_view'),
    path('tovar/', TovarListView.as_view(), name='tovar_list'),
    path('tovar/<int:pk>/', TovarDetailView.as_view(), name='tovar_detail'),
    path('tovar/create/', TovarCreateView.as_view(), name='tovar_create'),
    path('tovar/<int:pk>/update/', TovarUpdateView.as_view(), name='tovar_update'),
    path('tovar/<int:pk>/delete/', TovarDeleteView.as_view(), name='tovar_delete'),
    path('category/', CategoryListView.as_view(), name='category_list'),
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/update/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('brend/', BrendListView.as_view(), name='brend_list'),
    path('brend/<int:pk>/', BrendDetailView.as_view(), name='brend_detail'),
    path('brend/create/', BrendCreateView.as_view(), name='brend_create'),
    path('brend/<int:pk>/update/', BrendUpdateView.as_view(), name='brend_update'),
    path('brend/<int:pk>/delete/', BrendDeleteView.as_view(), name='brend_delete'),
    path('tovartype/', TovarTypeListView.as_view(), name='tovartype_list'),
    path('tovartype/<int:pk>/', TovarTypeDetailView.as_view(), name='tovartype_detail'),
    path('tovartype/create/', TovarTypeCreateView.as_view(), name='tovartype_create'),
    path('tovartype/<int:pk>/update/', TovarTypeUpdateView.as_view(), name='tovartype_update'),
    path('tovartype/<int:pk>/delete/', TovarTypeDeleteView.as_view(), name='tovartype_delete'),
    path('news/', NewsListView.as_view(), name='news_list'),
    path('news/<int:pk>/', NewsDetailView.as_view(), name='news_detail'),
    path('news/create/', NewsCreateView.as_view(), name='news_create'),
    path('news/<int:pk>/update/', NewsUpdateView.as_view(), name='news_update'),
    path('news/<int:pk>/delete/', NewsDeleteView.as_view(), name='news_delete'),
    path('review/', ReviewListView.as_view(), name='review_list'),
    path('review/<int:pk>/', ReviewDetailView.as_view(), name='review_detail'),
    path('review/create/', ReviewCreateView.as_view(), name='review_create'),
    path('review/<int:pk>/update/', ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
    path('promotion/', PromotionListView.as_view(), name='promotion_list'),
    path('promotion/<int:pk>/', PromotionDetailView.as_view(), name='promotion_detail'),
    path('promotion/create/', PromotionCreateView.as_view(), name='promotion_create'),
    path('promotion/<int:pk>/update/', PromotionUpdateView.as_view(), name='promotion_update'),
    path('promotion/<int:pk>/delete/', PromotionDeleteView.as_view(), name='promotion_delete'),
    path('collection/', CollectionListView.as_view(), name='collection_list'),
    path('collection/<int:pk>/', CollectionDetailView.as_view(), name='collection_detail'),
    path('collection/create/', CollectionCreateView.as_view(), name='collection_create'),
    path('collection/<int:pk>/update/', CollectionUpdateView.as_view(), name='collection_update'),
    path('collection/<int:pk>/delete/', CollectionDeleteView.as_view(), name='collection_delete'),
]